# Generated by Django 2.1.4 on 2020-09-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='crepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('img', models.ImageField(default='media/default.png', upload_to='app')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='my_app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(default='media/default.png', upload_to='app')),
            ],
        ),
        migrations.CreateModel(
            name='point_de_vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='commande',
            field=models.ManyToManyField(blank=True, to='my_app.crepe'),
        ),
        migrations.AddField(
            model_name='clients',
            name='mode_de_livraison',
            field=models.ManyToManyField(blank=True, null=True, to='my_app.livraison'),
        ),
        migrations.AddField(
            model_name='clients',
            name='point_de_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.point_de_vente'),
        ),
    ]
