# Generated by Django 2.1.4 on 2020-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_livraison_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='num',
            field=models.IntegerField(blank=True),
        ),
    ]
