# Generated by Django 2.1.4 on 2020-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200902_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='mode_de_livraison',
            field=models.ManyToManyField(blank=True, to='my_app.livraison'),
        ),
    ]
