# Generated by Django 2.1.4 on 2020-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200902_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
