# Generated by Django 2.1.4 on 2020-09-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200902_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='point_de_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.point_de_vente'),
        ),
    ]
