# Generated by Django 2.1.4 on 2020-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200902_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
