# Generated by Django 2.1.4 on 2020-09-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_clients_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='total',
        ),
    ]
