# Generated by Django 2.1.4 on 2020-09-02 22:35

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('my_app', '0011_remove_clients_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crepe',
            new_name='menu',
        ),
    ]
